/* -*- c++ -*- */
/*
 * Copyright 2013 Lizhao You
 */

#ifndef INCLUDED_PNC_TAGS_H
#define INCLUDED_PNC_TAGS_H

enum {NO_USER_MODE, USER_MODE, USER_A_MODE, USER_B_MODE, TWO_USER_MODE};


// generated by USRP block
static const pmt::pmt_t TIME_KEY = pmt::string_to_symbol("rx_time");	// usrp init timestamp
static const pmt::pmt_t PCTIME_KEY = pmt::string_to_symbol("rx_pctime");
static const pmt::pmt_t RATE_KEY = pmt::string_to_symbol("rx_rate");

static const pmt::pmt_t SYNC_TIME = pmt::string_to_symbol("sync_time");

// generated by raw_regenerate_peak blocks
static const pmt::pmt_t PEAK_SU_CFO = pmt::string_to_symbol("peak_su_cfo");
static const pmt::pmt_t PEAK_MU_CFO = pmt::string_to_symbol("peak_mu_cfo");
static const pmt::pmt_t PKT_DECODE_TIME = pmt::string_to_symbol("pkt_decode_time");

// generated by raw_sampler block
static const pmt::pmt_t SAMPLER_NOISE_KEY = pmt::string_to_symbol("sampler_noise_power");
static const pmt::pmt_t SAMPLER_HW_TIME = pmt::string_to_symbol("sampler_hw_time");
static const pmt::pmt_t SAMPLER_PC_TIME = pmt::string_to_symbol("sampler_pc_time");
static const pmt::pmt_t SAMPLER_SU_CFO = pmt::string_to_symbol("sampler_su_cfo");
static const pmt::pmt_t SAMPLER_MU_CFO = pmt::string_to_symbol("sampler_mu_cfo");
static const pmt::pmt_t SAMPLER_SU_SNR = pmt::string_to_symbol("sampler_su_snr");
static const pmt::pmt_t SAMPLER_MU_SNR = pmt::string_to_symbol("sampler_mu_snr");

// generated by raw_ofdm_demod and raw_pnc_demod block
static const pmt::pmt_t SYNC_HW_TIME = pmt::string_to_symbol("sync_hw_time");
static const pmt::pmt_t SYNC_PC_TIME = pmt::string_to_symbol("sync_pc_time");
static const pmt::pmt_t SYNC_SU_CFO = pmt::string_to_symbol("sync_su_cfo");
static const pmt::pmt_t SYNC_MU_CFO = pmt::string_to_symbol("sync_mu_cfo");
static const pmt::pmt_t SYNC_SU_SNR = pmt::string_to_symbol("sync_su_snr");
static const pmt::pmt_t SYNC_MU_SNR = pmt::string_to_symbol("sync_mu_snr");
//static const pmt::pmt_t SNR_SU_KEYS = pmt::pmt_string_to_symbol("rx_su_snrs");

// generated by raw_pnc_demod block
static const pmt::pmt_t POWER_KEY1 = pmt::string_to_symbol("rx_power_1");
static const pmt::pmt_t POWER_KEY2 = pmt::string_to_symbol("rx_power_2");
static const pmt::pmt_t POWER_KEY3 = pmt::string_to_symbol("rx_power_3");

#endif /* INCLUDED_PNC_TAGS_H */
